/**
 * Figma source-of-truth registry for PDS subcomponents.
 * Update this file whenever a component is added, renamed, or superseded.
 */
export type ComponentLifecycleStatus =
  | "active"
  | "deprecated"
  | "experimental"
  | "superseded";

export type FigmaComponentRegistryEntry = {
  id: string;
  name: string;
  figmaNodeId: string;
  figmaFileKey: string;
  codePath: string;
  status: ComponentLifecycleStatus;
  dependsOn?: string[];
  supersededBy?: string;
  introducedIn: string;
  notes?: string;
};

export const FIGMA_FILE_KEY = "ijAgEelM6OgifzPI0R5BoQ";

export const PDS_COMPONENT_REGISTRY: FigmaComponentRegistryEntry[] = [
  {
    id: "radio-box",
    name: "Radio Box",
    figmaNodeId: "35:14634",
    figmaFileKey: FIGMA_FILE_KEY,
    codePath: "apps/web/components/pds/subcomponents/radio-box.tsx",
    status: "active",
    introducedIn: "2026-06-19",
  },
  {
    id: "check-box",
    name: "Checkbox",
    figmaNodeId: "35:14933",
    figmaFileKey: FIGMA_FILE_KEY,
    codePath: "apps/web/components/pds/subcomponents/check-box.tsx",
    status: "active",
    introducedIn: "2026-06-19",
  },
  {
    id: "check-list-item",
    name: "CheckListItem",
    figmaNodeId: "35:13709",
    figmaFileKey: FIGMA_FILE_KEY,
    codePath: "apps/web/components/pds/subcomponents/check-list-item.tsx",
    status: "active",
    dependsOn: ["check-box"],
    introducedIn: "2026-06-19",
    notes: "Full-row selectable list item for CheckboxList; background changes on selection.",
  },
  {
    id: "button",
    name: "Button",
    figmaNodeId: "2:95",
    figmaFileKey: FIGMA_FILE_KEY,
    codePath: "apps/web/components/ui/button.tsx",
    status: "active",
    introducedIn: "2026-06-19",
    notes: "Global subcomponent. Used in Options footer, forms, tables, heroes — not nested under Select only.",
  },
  {
    id: "divider",
    name: "Divider",
    figmaNodeId: "35:14443",
    figmaFileKey: FIGMA_FILE_KEY,
    codePath: "apps/web/components/pds/subcomponents/divider.tsx",
    status: "active",
    introducedIn: "2026-06-19",
  },
  {
    id: "option-item-default",
    name: "option-items/default",
    figmaNodeId: "35:13664",
    figmaFileKey: FIGMA_FILE_KEY,
    codePath: "apps/web/components/pds/composites/option-item.tsx",
    status: "active",
    dependsOn: ["divider"],
    introducedIn: "2026-06-19",
  },
  {
    id: "option-item-radio",
    name: "option-items/radio",
    figmaNodeId: "35:13688",
    figmaFileKey: FIGMA_FILE_KEY,
    codePath: "apps/web/components/pds/composites/option-item.tsx",
    status: "active",
    dependsOn: ["radio-box", "divider"],
    introducedIn: "2026-06-19",
  },
  {
    id: "option-item-checkbox",
    name: "option-items/checkbox",
    figmaNodeId: "35:13709",
    figmaFileKey: FIGMA_FILE_KEY,
    codePath: "apps/web/components/pds/composites/option-item.tsx",
    status: "active",
    dependsOn: ["check-box", "divider"],
    introducedIn: "2026-06-19",
  },
  {
    id: "options",
    name: "Options",
    figmaNodeId: "35:13598",
    figmaFileKey: FIGMA_FILE_KEY,
    codePath: "apps/web/components/pds/composites/options.tsx",
    status: "active",
    dependsOn: ["option-item-default", "button"],
    introducedIn: "2026-06-19",
    notes: "Standalone list panel. Used in PdsSelect, filter popovers, multi-select sheets, or any anchored menu.",
  },
  {
    id: "select-item-position",
    name: "Select_Item/position",
    figmaNodeId: "35:12288",
    figmaFileKey: FIGMA_FILE_KEY,
    codePath: "apps/web/components/pds/composites/select-item-position.tsx",
    status: "active",
    introducedIn: "2026-06-19",
    notes: "Layout shell only. Accepts any children; Options is a common default via optionsProps.",
  },
  {
    id: "select",
    name: "Select",
    figmaNodeId: "35:12158",
    figmaFileKey: FIGMA_FILE_KEY,
    codePath: "apps/web/components/pds/composites/select.tsx",
    status: "active",
    dependsOn: ["select-item-position", "options"],
    introducedIn: "2026-06-19",
    notes: "Feature assembly. Composes trigger + positioned panel; does not own Options or Button exclusively.",
  },
  {
    id: "checkbox-list",
    name: "CheckboxList",
    figmaNodeId: "composite",
    figmaFileKey: FIGMA_FILE_KEY,
    codePath: "apps/web/components/pds/composites/checkbox-list.tsx",
    status: "active",
    dependsOn: ["check-list-item", "check-box", "button"],
    introducedIn: "2026-06-19",
    notes: "Multi-select card list with header checkbox, select-all, CheckListItem rows, optional amounts footer.",
  },
  {
    id: "modal",
    name: "Modal",
    figmaNodeId: "47:2950",
    figmaFileKey: FIGMA_FILE_KEY,
    codePath: "apps/web/components/pds/composites/modal.tsx",
    status: "active",
    dependsOn: ["button"],
    introducedIn: "2026-06-19",
    notes: "Centered dialog wrapper (header + body slots + footer). ConfirmDialog is a thin preset in shared.",
  },
  {
    id: "status-pill",
    name: "StatusPill",
    figmaNodeId: "composite",
    figmaFileKey: FIGMA_FILE_KEY,
    codePath: "apps/web/components/pds/subcomponents/status-pill.tsx",
    status: "active",
    introducedIn: "2026-06-19",
    notes: "Semantic status pills — paid, partial, overdue, due, scholarship, active, inactive.",
  },
  {
    id: "attendance-toggle",
    name: "AttendanceToggle",
    figmaNodeId: "composite",
    figmaFileKey: FIGMA_FILE_KEY,
    codePath: "apps/web/components/pds/subcomponents/attendance-toggle.tsx",
    status: "active",
    introducedIn: "2026-06-19",
    notes: "Large attendance choice buttons — present, late, absent with status icon.",
  },
  {
    id: "icon-tile",
    name: "IconTile",
    figmaNodeId: "composite",
    figmaFileKey: FIGMA_FILE_KEY,
    codePath: "apps/web/components/pds/subcomponents/icon-tile.tsx",
    status: "active",
    introducedIn: "2026-06-19",
    notes: "Tinted square tile + matching filled icon for row/card identity.",
  },
  {
    id: "subject-chip",
    name: "SubjectChip",
    figmaNodeId: "composite",
    figmaFileKey: FIGMA_FILE_KEY,
    codePath: "apps/web/components/pds/subcomponents/subject-chip.tsx",
    status: "active",
    introducedIn: "2026-06-19",
    notes: "Categorical solid-color subject encoding chips.",
  },
  {
    id: "grade-chip",
    name: "GradeChip",
    figmaNodeId: "composite",
    figmaFileKey: FIGMA_FILE_KEY,
    codePath: "apps/web/components/pds/subcomponents/grade-chip.tsx",
    status: "active",
    introducedIn: "2026-06-19",
    notes: "Grade letter chips with tinted bg + saturated text.",
  },
  {
    id: "filter-tabs",
    name: "FilterTabs",
    figmaNodeId: "composite",
    figmaFileKey: FIGMA_FILE_KEY,
    codePath: "apps/web/components/pds/composites/filter-tabs.tsx",
    status: "active",
    introducedIn: "2026-06-19",
    notes: "FilterTab (count pill), SubjectTab (categorical fill), DayPickerTab (emphasis lime).",
  },
  {
    id: "segmented-control",
    name: "SegmentedControl",
    figmaNodeId: "67:13138",
    figmaFileKey: FIGMA_FILE_KEY,
    codePath: "apps/web/components/pds/composites/segmented-control.tsx",
    status: "active",
    introducedIn: "2026-06-19",
    notes: "Canvas track, soft border, 12px radius; active segment primary pill with invert text.",
  },
  {
    id: "search-bar",
    name: "Search bar",
    figmaNodeId: "76:9646",
    figmaFileKey: FIGMA_FILE_KEY,
    codePath: "apps/web/components/pds/composites/search-bar.tsx",
    status: "active",
    introducedIn: "2026-06-19",
    notes: "Filter/table search — placeholder left, trailing search icon (320px in toolbar rows).",
  },
  {
    id: "search-filters-row",
    name: "Search and Filters",
    figmaNodeId: "76:9645",
    figmaFileKey: FIGMA_FILE_KEY,
    codePath: "apps/web/components/pds/composites/search-filters-row.tsx",
    status: "active",
    dependsOn: ["search-bar", "segmented-control"],
    introducedIn: "2026-06-19",
    notes: "Toolbar row — left filter cluster, right status segmented control.",
  },
  {
    id: "breadcrumb",
    name: "Breadcrumb",
    figmaNodeId: "67:14078",
    figmaFileKey: FIGMA_FILE_KEY,
    codePath: "apps/web/components/pds/composites/breadcrumb.tsx",
    status: "active",
    dependsOn: ["breadcrumb-item"],
    introducedIn: "2026-06-19",
    notes: "2–5 item trail; previous items linkable, current item terminal.",
  },
  {
    id: "top-nav-bar",
    name: "TopNavBar",
    figmaNodeId: "119:9730",
    figmaFileKey: FIGMA_FILE_KEY,
    codePath: "apps/web/components/pds/composites/top-nav-bar.tsx",
    status: "active",
    dependsOn: ["breadcrumb", "segmented-control"],
    introducedIn: "2026-06-21",
    notes: "Dashboard top bar — breadcrumb left; locale segmented control, academic year, notifications right.",
  },
  {
    id: "breadcrumb-item",
    name: "BreadcrumbItem",
    figmaNodeId: "67:14072",
    figmaFileKey: FIGMA_FILE_KEY,
    codePath: "apps/web/components/pds/subcomponents/breadcrumb-item.tsx",
    status: "active",
    introducedIn: "2026-06-19",
  },
  {
    id: "date-picker-trigger",
    name: "DatePickerTrigger",
    figmaNodeId: "67:14860",
    figmaFileKey: FIGMA_FILE_KEY,
    codePath: "apps/web/components/pds/subcomponents/date-picker-trigger.tsx",
    status: "active",
    introducedIn: "2026-06-19",
  },
  {
    id: "date-picker-nav-button",
    name: "DatePickerNavButton",
    figmaNodeId: "67:20063",
    figmaFileKey: FIGMA_FILE_KEY,
    codePath: "apps/web/components/pds/subcomponents/date-picker-nav-button.tsx",
    status: "active",
    introducedIn: "2026-06-19",
  },
  {
    id: "month-calendar-cell",
    name: "MonthCalendarCell",
    figmaNodeId: "67:13837",
    figmaFileKey: FIGMA_FILE_KEY,
    codePath: "apps/web/components/pds/subcomponents/month-calendar-cell.tsx",
    status: "active",
    introducedIn: "2026-06-19",
  },
  {
    id: "day-calendar-cell",
    name: "DayCalendarCell",
    figmaNodeId: "composite",
    figmaFileKey: FIGMA_FILE_KEY,
    codePath: "apps/web/components/pds/subcomponents/day-calendar-cell.tsx",
    status: "active",
    introducedIn: "2026-06-19",
  },
  {
    id: "month-calendar",
    name: "MonthCalendar",
    figmaNodeId: "67:14364",
    figmaFileKey: FIGMA_FILE_KEY,
    codePath: "apps/web/components/pds/composites/month-calendar.tsx",
    status: "active",
    dependsOn: ["date-picker-nav-button", "month-calendar-cell"],
    introducedIn: "2026-06-19",
  },
  {
    id: "date-calendar-header",
    name: "DateCalendarHeader",
    figmaNodeId: "67:14566",
    figmaFileKey: FIGMA_FILE_KEY,
    codePath: "apps/web/components/pds/subcomponents/date-calendar-header.tsx",
    status: "active",
    dependsOn: ["date-picker-nav-button"],
    introducedIn: "2026-06-19",
  },
  {
    id: "date-calendar-footer",
    name: "DateCalendarFooter",
    figmaNodeId: "67:14513",
    figmaFileKey: FIGMA_FILE_KEY,
    codePath: "apps/web/components/pds/subcomponents/date-calendar-footer.tsx",
    status: "active",
    dependsOn: ["button"],
    introducedIn: "2026-06-19",
  },
  {
    id: "date-calendar-shortcut-button",
    name: "DateCalendarShortcutButton",
    figmaNodeId: "67:14509",
    figmaFileKey: FIGMA_FILE_KEY,
    codePath: "apps/web/components/pds/subcomponents/date-calendar-shortcut-button.tsx",
    status: "active",
    introducedIn: "2026-06-19",
  },
  {
    id: "date-calendar-presets",
    name: "DateCalendarPresets",
    figmaNodeId: "67:14723",
    figmaFileKey: FIGMA_FILE_KEY,
    codePath: "apps/web/components/pds/subcomponents/date-calendar-presets.tsx",
    status: "active",
    dependsOn: ["date-calendar-shortcut-button"],
    introducedIn: "2026-06-19",
  },
  {
    id: "date-calendar-month-grid",
    name: "DateCalendarMonthGrid",
    figmaNodeId: "67:14567",
    figmaFileKey: FIGMA_FILE_KEY,
    codePath: "apps/web/components/pds/subcomponents/date-calendar-month-grid.tsx",
    status: "active",
    dependsOn: ["date-calendar-header", "day-calendar-cell"],
    introducedIn: "2026-06-19",
  },
  {
    id: "date-calendar-filter-footer",
    name: "DateCalendarFilterFooter",
    figmaNodeId: "67:14836",
    figmaFileKey: FIGMA_FILE_KEY,
    codePath: "apps/web/components/pds/subcomponents/date-calendar-filter-footer.tsx",
    status: "active",
    dependsOn: ["button"],
    introducedIn: "2026-06-19",
  },
  {
    id: "filter-range-calendar",
    name: "FilterRangeCalendar",
    figmaNodeId: "67:14722",
    figmaFileKey: FIGMA_FILE_KEY,
    codePath: "apps/web/components/pds/composites/filter-range-calendar.tsx",
    status: "active",
    dependsOn: ["date-calendar-presets", "date-calendar-month-grid", "date-calendar-filter-footer"],
    introducedIn: "2026-06-19",
    notes: "Filter variant with preset shortcuts and two month panels.",
  },
  {
    id: "date-calendar",
    name: "DateCalendar",
    figmaNodeId: "67:14512",
    figmaFileKey: FIGMA_FILE_KEY,
    codePath: "apps/web/components/pds/composites/date-calendar.tsx",
    status: "active",
    dependsOn: ["date-calendar-header", "date-calendar-footer", "date-calendar-month-grid"],
    introducedIn: "2026-06-19",
    notes: "Single-day and range day grids; static or dynamic header.",
  },
  {
    id: "day-calendar",
    name: "DayCalendar",
    figmaNodeId: "67:14513",
    figmaFileKey: FIGMA_FILE_KEY,
    codePath: "apps/web/components/pds/composites/day-calendar.tsx",
    status: "active",
    dependsOn: ["date-calendar"],
    introducedIn: "2026-06-19",
    notes: "Thin wrapper over DateCalendar (default variant).",
  },
  {
    id: "date-picker",
    name: "DatePicker",
    figmaNodeId: "67:14870",
    figmaFileKey: FIGMA_FILE_KEY,
    codePath: "apps/web/components/pds/composites/date-picker.tsx",
    status: "active",
    dependsOn: ["date-picker-trigger", "month-calendar", "date-calendar", "filter-range-calendar", "date-picker-position"],
    introducedIn: "2026-06-19",
    notes: "Form + filter; day/month; single or range; static or dynamic calendar header.",
  },
  {
    id: "entity-avatar",
    name: "EntityAvatar",
    figmaNodeId: "composite",
    figmaFileKey: FIGMA_FILE_KEY,
    codePath: "apps/web/components/pds/subcomponents/entity-avatar.tsx",
    status: "active",
    introducedIn: "2026-06-19",
    notes: "Color-blocked squircle avatar (icon or initials) for entity list rows.",
  },
  {
    id: "entity-list",
    name: "EntityList",
    figmaNodeId: "composite",
    figmaFileKey: FIGMA_FILE_KEY,
    codePath: "apps/web/components/pds/composites/entity-list.tsx",
    status: "active",
    dependsOn: ["entity-avatar"],
    introducedIn: "2026-06-19",
    notes: "Card-style vertical list: avatar + title/meta + optional Open action. Replaces RecordList.",
  },
  {
    id: "detail-card-avatar",
    name: "DetailCardAvatar",
    figmaNodeId: "75:9199",
    figmaFileKey: FIGMA_FILE_KEY,
    codePath: "apps/web/components/pds/subcomponents/detail-card-avatar.tsx",
    status: "active",
    introducedIn: "2026-06-19",
  },
  {
    id: "detail-card-status",
    name: "DetailCardStatus",
    figmaNodeId: "75:9199",
    figmaFileKey: FIGMA_FILE_KEY,
    codePath: "apps/web/components/pds/subcomponents/detail-card-status.tsx",
    status: "active",
    introducedIn: "2026-06-19",
  },
  {
    id: "detail-card-tag",
    name: "DetailCardTag",
    figmaNodeId: "75:9199",
    figmaFileKey: FIGMA_FILE_KEY,
    codePath: "apps/web/components/pds/subcomponents/detail-card-tag.tsx",
    status: "active",
    introducedIn: "2026-06-19",
  },
  {
    id: "detail-card",
    name: "DetailCard",
    figmaNodeId: "75:9199",
    figmaFileKey: FIGMA_FILE_KEY,
    codePath: "apps/web/components/pds/composites/detail-card.tsx",
    status: "active",
    dependsOn: ["detail-card-avatar", "detail-card-status", "detail-card-tag", "button"],
    introducedIn: "2026-06-19",
    notes: "Ink-green profile/entity hero for students, teachers, academic structure. Replaces structure-room-banner and teacher profile hero.",
  },
  {
    id: "info-card-badge",
    name: "InfoCardBadge",
    figmaNodeId: "67:13145",
    figmaFileKey: FIGMA_FILE_KEY,
    codePath: "apps/web/components/pds/subcomponents/info-card-badge.tsx",
    status: "active",
    introducedIn: "2026-06-19",
  },
  {
    id: "info-card",
    name: "InfoCard",
    figmaNodeId: "67:13145",
    figmaFileKey: FIGMA_FILE_KEY,
    codePath: "apps/web/components/pds/composites/info-card.tsx",
    status: "active",
    dependsOn: ["info-card-badge"],
    introducedIn: "2026-06-19",
    notes: "Dark feature/rule callout card. Distinct from DetailCard and invoice stat strips.",
  },
  {
    id: "select-field",
    name: "SelectField",
    figmaNodeId: "35:12158",
    figmaFileKey: FIGMA_FILE_KEY,
    codePath: "apps/web/components/pds/fields/select-field.tsx",
    status: "active",
    dependsOn: ["select"],
    introducedIn: "2026-06-19",
    notes: "Options-array wrapper for forms and filters. Replaces FormSelect and native select.",
  },
  {
    id: "empty-state",
    name: "EmptyState",
    figmaNodeId: "54:2584",
    figmaFileKey: FIGMA_FILE_KEY,
    codePath: "apps/web/components/shared/empty-state.tsx",
    status: "active",
    dependsOn: ["button"],
    introducedIn: "2026-06-21",
    notes: "Comfort (default) and compact variants. Use embedded when nested in table-card body.",
  },
  {
    id: "invoice-details",
    name: "InvoiceDetails",
    figmaNodeId: "127:8304",
    figmaFileKey: FIGMA_FILE_KEY,
    codePath: "apps/web/components/pds/composites/invoice-details.tsx",
    status: "active",
    introducedIn: "2026-06-21",
    notes: "Line-item breakdown sections with total-due footer for invoices and enrollment preview.",
  },
  {
    id: "modal-header-shell",
    name: "ModalHeaderShell",
    figmaNodeId: "127:16021",
    figmaFileKey: FIGMA_FILE_KEY,
    codePath: "apps/web/components/pds/composites/modal-header-shell.tsx",
    status: "active",
    dependsOn: ["stepper"],
    introducedIn: "2026-06-21",
    notes: "Modal header variants: default, withStepper (enrollment ceremony), invoice (finance document).",
  },
  {
    id: "invoice",
    name: "Invoice",
    figmaNodeId: "127:16147",
    figmaFileKey: FIGMA_FILE_KEY,
    codePath: "apps/web/components/pds/composites/invoice.tsx",
    status: "active",
    dependsOn: ["invoice-details", "modal-header-shell"],
    introducedIn: "2026-06-21",
    notes: "Full invoice document shell composed of invoice header, billed-to meta, and InvoiceDetails.",
  },
  {
    id: "toggle-list-item",
    name: "ToggleListItem",
    figmaNodeId: "127:5528",
    figmaFileKey: FIGMA_FILE_KEY,
    codePath: "apps/web/components/pds/composites/toggle-list.tsx",
    status: "active",
    dependsOn: ["toggle"],
    introducedIn: "2026-06-21",
    notes: "Locked, toggle, and expandable row variants. Toggle enabled 127:21707, disabled 127:21725. Expandable eligibility 132:33687.",
  },
];

export function getRegistryEntry(id: string) {
  return PDS_COMPONENT_REGISTRY.find((entry) => entry.id === id);
}
